include!("tools/types.rs");
include!("tools/xcap_screenshot.rs");
include!("tools/screenshot_mcp.rs");
include!("tools/wait.rs");
include!("tools/terminal.rs");
include!("tools/patch.rs");
include!("tools/patch_rewind.rs");
include!("tools/read_file.rs");
include!("tools/read_file_mcp.rs");
