
<template>
  <div class="window-shell text-sm bg-base-200">
    <AppWindowHeader
      :view-mode="viewMode"
      :detached-chat-window="detachedChatWindow"
      :current-theme="currentTheme"
      :title-text="titleText"
      :chat-usage-percent="chatUsagePercent"
      :trimming="trimming"
      :chatting="chatting"
      :current-persona-name="String(currentForegroundPersona?.name || '').trim() || t('archives.roleAssistant')"
      :side-conversation-list-visible="sideConversationListVisible"
      :tool-review-panel-open-visible="toolReviewPanelOpenVisible"
      :chat-side-panel-widths="chatSidePanelWidths"
      :conversation-list-tab="conversationListTab"
      :chat-left-panel-mode="chatLeftPanelMode"
      :chat-right-panel-mode="chatRightPanelMode"
      :active-conversation-id="currentChatConversationId"
      :conversation-items="chatConversationItems"
      :current-chat-workspaces="chatWorkspaceChoices"
      :user-alias="userAlias"
      :user-avatar-url="userAvatarUrl"
      :persona-name-map="chatPersonaNameMap"
      :persona-avatar-url-map="chatPersonaAvatarUrlMap"
      :create-conversation-department-options="createConversationDepartmentOptions"
      :default-create-conversation-department-id="defaultCreateConversationDepartmentId"
      :trim-tip="t('chat.trimTip')"
      :maximized="maximized"
      :window-ready="windowReady"
      :open-settings-title="t('window.configTitle')"
      :close-title="t('common.close')"
      :config-search-query="configSearchQuery"
      :config-search-results="configSearchResults"
      :config-search-placeholder="t('config.search.placeholder')"
      :show-update-to-latest-button="showUpdateToLatestButton"
      :has-available-update="hasAvailableUpdate"
      :checking-update="checkingUpdate"
      :update-to-latest-label="updateToLatestLabel"
      :update-to-latest-title="updateToLatestTitle"
      @open-archives="openConversationList"
      @open-settings="openSettingsWindow"
      @minimize-window="minimizeWindowAndClearForeground"
      @toggle-maximize-window="toggleMaximizeWindow"
      @update:config-search-query="updateConfigSearchQuery"
      @select-config-search-result="handleSelectConfigSearchResult"
      @update-to-latest="triggerUpdateToLatest"
      @toggle-side-conversation-list="toggleSideConversationList"
      @toggle-tool-review-panel="toggleToolReviewPanel"
      @update:conversation-list-tab="updateConversationListTab"
      @update:chat-left-panel-mode="updateChatLeftPanelMode"
      @update:chat-right-panel-mode="updateChatRightPanelMode"
      @switch-conversation="switchChatConversation"
      @rename-conversation="renameCurrentConversation"
      @toggle-pin-conversation="toggleConversationPin"
      @archive-conversation="archiveConversationFromList"
      @delete-conversation="deleteUnarchivedConversationFromArchives"
      @create-conversation="createUnarchivedConversation"
      @trim-conversation="openTrimActionDialog"
      @start-drag="startDrag"
      @close-window="handleCloseWindow"
    />

    <AppWindowContent
      :t="tr"
      :view-mode="viewMode"
      :detached-chat-window="detachedChatWindow"
      :side-conversation-list-visible="sideConversationListVisible"
      :initial-tool-review-panel-open="toolReviewPanelOpenVisible"
      :conversation-list-tab="conversationListTab"
      :chat-left-panel-mode="chatLeftPanelMode"
      :chat-right-panel-mode="chatRightPanelMode"
      :config="config"
      :config-tab="configTab"
      :locale-options="localeOptions"
      :current-theme="currentTheme"
      :generated-theme-controls="generatedThemeControls"
      :generated-theme-tokens="generatedThemeTokens"
      :on-refresh-tool-review-message="refreshForegroundConversationMessageById"
      :selected-api-config="selectedApiConfig"
      :tool-api-config="toolApiConfig"
      :base-url-reference="baseUrlReference"
      :refreshing-models="refreshingModels"
      :selected-model-options="selectedModelOptions"
      :model-refresh-ok="selectedModelRefreshOk"
      :model-refresh-error="modelRefreshError"
      :tool-statuses="toolStatuses"
      :personas="personas"
      :assistant-personas="assistantPersonas"
      :user-persona="userPersona"
      :persona-editor-id="personaEditorId"
      :assistant-department-agent-id="assistantDepartmentAgentId"
      :selected-persona-editor="selectedPersonaEditor"
      :tool-persona="selectedPersonaEditor"
      :selected-persona-editor-avatar-url="selectedPersonaEditorAvatarUrl"
      :user-persona-avatar-url="userPersonaAvatarUrl"
      :response-style-options="responseStyleOptions"
      :selected-response-style-id="selectedResponseStyleId"
      :selected-pdf-read-mode="selectedPdfReadMode"
      :background-voice-screenshot-keywords="backgroundVoiceScreenshotKeywords"
      :background-voice-screenshot-mode="backgroundVoiceScreenshotMode"
      :text-capable-api-configs="textCapableApiConfigs"
      :image-capable-api-configs="imageCapableApiConfigs"
      :stt-capable-api-configs="sttCapableApiConfigs"
      :image-cache-stats="imageCacheStats"
      :image-cache-stats-loading="imageCacheStatsLoading"
      :avatar-saving="avatarSaving"
      :avatar-error="avatarError"
      :persona-saving="personaSaving"
      :persona-dirty="personaDirty"
      :config-dirty="configDirty"
      :saving="saving"
      :normalize-api-bindings-action="normalizeApiBindingsLocal"
      :hotkey-test-recording="hotkeyTestRecording"
      :hotkey-test-recording-ms="hotkeyTestRecordingMs"
      :hotkey-test-audio="hotkeyTestAudio"
      :user-alias="userAlias"
      :selected-persona-name="currentForegroundPersona?.name || t('archives.roleAssistant')"
      :current-chat-workspace-name="chatWorkspaceName"
      :current-chat-workspace-root-path="chatWorkspaceRootPath"
      :current-chat-workspaces="chatWorkspaceChoices"
      :current-chat-department-id="currentForegroundDepartmentId"
      :user-avatar-url="userAvatarUrl"
      :selected-persona-avatar-url="currentForegroundPersonaAvatarUrl"
      :chat-persona-name-map="chatPersonaNameMap"
      :chat-persona-avatar-url-map="chatPersonaAvatarUrlMap"
      :chat-mention-entries="chatMentionEntries"
      :selected-chat-mentions="selectedChatMentions"
      :latest-user-text="latestUserText"
      :latest-user-images="latestUserImages"
      :latest-assistant-text="latestAssistantText"
      :latest-reasoning-standard-text="latestReasoningStandardText"
      :latest-reasoning-inline-text="latestReasoningInlineText"
      :frontend-round-phase="chatFlow.frontendRoundPhase.value"
      :tool-status-text="toolStatusText"
      :tool-status-state="toolStatusState"
      :stream-tool-calls="streamToolCalls"
      :chat-error-text="chatErrorText"
      :clipboard-images="clipboardImages"
      :queued-attachment-notices="queuedAttachmentNotices"
      :chat-input="chatInput"
      :instruction-presets="instructionPresets"
      :chat-input-placeholder="chatInputPlaceholder"
      :speech-recognition-supported="speechRecognitionSupported"
      :recording="recording"
      :recording-ms="recordingMs"
      :transcribing="transcribing"
      :record-hotkey="config.recordHotkey"
      :selected-chat-model-id="currentForegroundApiConfigId"
      :tool-review-refresh-tick="toolReviewRefreshTick"
      :terminal-approvals="terminalApprovalConversationItems"
      :terminal-approval-resolving="terminalApprovalResolving"
      :approve-terminal-approval="approveTerminalApproval"
      :deny-terminal-approval="denyTerminalApproval"
      :plan-mode-enabled="currentConversationPlanModeEnabled"
      :chat-usage-percent="chatUsagePercent"
      :trim-tip="t('chat.trimTip')"
      :media-drag-active="mediaDragActive"
      :chatting="chatting"
      :trimming="trimming"
      :trimming-conversation-id="trimmingConversationId"
      :compacting-conversation="compactingConversation"
      :compacting-conversation-id="compactingConversationId"
      :branching-conversation="branchingConversation"
      :forwarding-conversation-selection="forwardingConversationSelection"
      :visible-message-blocks="displayMessageBlocks"
      :chat-has-more-history="hasMoreBackendHistory"
      :chat-loading-older-history="loadingOlderConversationHistory"
      :latest-own-message-align-request="latestOwnMessageAlignRequest"
      :conversation-scroll-to-bottom-request="conversationScrollToBottomRequest"
      :current-chat-conversation-id="currentChatConversationId"
      :current-chat-todos="currentChatTodos"
      :chat-supervision-active="chatSupervisionActive"
      :chat-supervision-title="chatSupervisionTitle"
      :supervision-task-dialog-open="supervisionTaskDialogOpen"
      :supervision-task-saving="supervisionTaskSaving"
      :supervision-task-error="supervisionTaskError"
      :active-supervision-task="activeSupervisionTask"
      :recent-supervision-task-history="recentSupervisionTaskHistory"
      :chat-unarchived-conversation-items="chatUnarchivedConversationItems"
      :chat-conversation-items="chatConversationItems"
      :create-conversation-department-options="createConversationDepartmentOptions"
      :delegate-department-ids="delegateDepartmentIds"
      :default-create-conversation-department-id="defaultCreateConversationDepartmentId"
      :archives="archives"
      :selected-archive-id="selectedArchiveId"
      :archive-blocks="archiveBlocks"
      :selected-archive-block-id="selectedArchiveBlockId"
      :archive-has-prev-block="archiveHasPrevBlock"
      :archive-has-next-block="archiveHasNextBlock"
      :archive-messages="archiveMessages"
      :archive-summary-text="archiveSummaryText"
      :unarchived-conversations="unarchivedConversations"
      :unarchived-blocks="unarchivedBlocks"
      :selected-unarchived-conversation-id="selectedUnarchivedConversationId"
      :selected-unarchived-block-id="selectedUnarchivedBlockId"
      :unarchived-has-prev-block="unarchivedHasPrevBlock"
      :unarchived-has-next-block="unarchivedHasNextBlock"
      :unarchived-messages="unarchivedMessages"
      :delegate-conversations="delegateConversations"
      :selected-delegate-conversation-id="selectedDelegateConversationId"
      :delegate-messages="delegateMessages"
      :remote-im-contact-conversations="remoteImContactConversations"
      :remote-im-contact-blocks="remoteImContactBlocks"
      :selected-remote-im-contact-id="selectedRemoteImContactId"
      :selected-remote-im-contact-block-id="selectedRemoteImContactBlockId"
      :remote-im-has-prev-block="remoteImHasPrevBlock"
      :remote-im-has-next-block="remoteImHasNextBlock"
      :remote-im-contact-messages="remoteImContactMessages"
      :message-text="messageText"
      :extract-message-images="extractMessageImages"
      :on-load-older-chat-history="loadOlderConversationHistory"
      :memory-list="memoryList"
      :memory-page="memoryPage"
      :memory-page-count="memoryPageCount"
      :paged-memories="pagedMemories"
      :prompt-preview-mode="promptPreviewMode"
      :prompt-preview-loading="promptPreviewLoading"
      :prompt-preview-text="promptPreviewText"
      :prompt-preview-latest-user-text="promptPreviewLatestUserText"
      :prompt-preview-latest-images="promptPreviewLatestImages"
      :prompt-preview-latest-audios="promptPreviewLatestAudios"
      :prompt-preview-conversation-id="promptPreviewConversationId"
      :prompt-preview-conversation-options="promptPreviewConversationOptions"
      :load-prompt-preview="loadPromptPreview"
      :select-prompt-preview-conversation="selectPromptPreviewConversation"
      :set-memory-dialog-ref="setMemoryDialogRef"
      :set-prompt-preview-dialog-ref="setPromptPreviewDialogRef"
      :set-status="setStatus"
      :attach-tool-review-report="attachToolReviewReport"
      :update-config-tab="(value) => { configTab = value; }"
      :set-ui-language="setUiLanguage"
      :update-persona-editor-id="updatePersonaEditorIdWithNotice"
      :update-selected-persona-id="updateAssistantDepartmentAgentId"
      :update-selected-response-style-id="updateSelectedResponseStyleId"
      :update-selected-pdf-read-mode="updateSelectedPdfReadMode"
      :update-background-voice-screenshot-keywords="updateBackgroundVoiceScreenshotKeywords"
      :update-background-voice-screenshot-mode="updateBackgroundVoiceScreenshotMode"
      :update-instruction-presets="updateInstructionPresets"
      :patch-conversation-api-settings="patchConversationApiSettings"
      :patch-chat-settings="patchChatSettings"
      :update-webview-zoom-percent="updateWebviewZoomPercent"
      :update-github-update-method="updateGithubUpdateMethod"
      :set-theme="setTheme"
      :activate-generated-theme="activateGeneratedTheme"
      :update-generated-theme-controls="updateGeneratedThemeControls"
      :reset-generated-theme="resetGeneratedTheme"
      :refresh-models="refreshModels"
      :on-tools-changed="handleToolsChanged"
      :save-config="saveConfig"
      :restore-config="restoreLastSavedConfigSnapshot"
      :add-api-config="addApiConfig"
      :remove-selected-api-config="removeSelectedApiConfig"
      :add-persona="addPersona"
      :remove-selected-persona="removeSelectedPersona"
      :reset-personas="loadPersonas"
      :save-personas="savePersonas"
      :import-persona-memories="importPersonaMemories"
      :open-conversation-list="openConversationList"
      :open-conversation-summary="openConversationSummary"
      :open-trim-action-dialog="openTrimActionDialog"
      :open-settings-window="openSettingsWindow"
      :open-prompt-preview="openPromptPreview"
      :open-system-prompt-preview="openSystemPromptPreview"
      :open-memory-viewer="openMemoryViewer"
      :refresh-image-cache-stats="refreshImageCacheStats"
      :clear-image-cache="clearImageCache"
      :open-runtime-logs="openRuntimeLogsDialog"
      :start-hotkey-record-test="startHotkeyRecordTest"
      :stop-hotkey-record-test="stopHotkeyRecordTest"
      :play-hotkey-record-test="playHotkeyRecordTest"
      :capture-hotkey="captureHotkey"
      :summon-chat-now="summonChatWindowFromConfig"
      :save-agent-avatar="saveAgentAvatar"
      :clear-agent-avatar="clearAgentAvatar"
      :update-chat-input="handleChatInputUpdate"
      :update-selected-instruction-prompts="updateSelectedInstructionPrompts"
      :add-chat-mention="addChatMention"
      :remove-chat-mention="removeChatMention"
      :update-selected-chat-model-id="updateAssistantDepartmentApiConfigId"
      :update-plan-mode-enabled="updatePlanModeEnabled"
      :set-side-conversation-list-visible="handleSideConversationListVisibleChange"
      :set-tool-review-panel-open="handleToolReviewPanelOpenChange"
      :set-chat-side-panel-widths="handleChatSidePanelWidthsChange"
      :update-conversation-list-tab="updateConversationListTab"
      :update-chat-left-panel-mode="updateChatLeftPanelMode"
      :update-chat-right-panel-mode="updateChatRightPanelMode"
      :remove-clipboard-image="removeClipboardImage"
      :remove-queued-attachment-notice="removeQueuedAttachmentNotice"
      :pick-attachments="pickChatAttachments"
      :start-recording="startRecording"
      :stop-recording="() => stopRecording(false)"
      :send-chat="sendChatFromCurrentWindow"
      :stop-chat="chatFlow.stopChat"
      :clear-chat-error="clearChatError"
      :on-jump-to-conversation-bottom="ensureLatestForegroundTailThenScrollToBottom"
      :open-supervision-task-dialog="openSupervisionTaskDialog"
      :on-detach-conversation="detachCurrentConversationToWindow"
      :close-supervision-task-dialog="closeSupervisionTaskDialog"
      :save-supervision-task="saveSupervisionTask"
      :on-reached-chat-bottom="() => undefined"
      :on-recall-turn="handleRecallTurn"
      :on-regenerate-turn="handleRegenerateTurn"
      :confirm-plan="handleConfirmPlan"
      :on-lock-chat-workspace="openChatWorkspacePicker"
      :on-switch-conversation="switchChatConversation"
      :on-rename-conversation="renameCurrentConversation"
      :on-toggle-conversation-pin="toggleConversationPin"
      :on-archive-conversation="archiveConversationFromList"
      :on-delete-conversation="deleteUnarchivedConversationFromArchives"
      :on-create-conversation="createUnarchivedConversation"
      :on-branch-conversation-from-selection="branchConversationFromSelection"
      :on-forward-conversation-from-selection="forwardConversationFromSelection"
      :on-user-async-delegate-from-selection="userAsyncDelegateFromSelection"
      :on-open-skill-panel="openSkillPlaceholderDialog"
      :load-archives="loadArchives"
      :select-archive="selectArchive"
      :select-archive-block="selectArchiveBlock"
      :select-unarchived-conversation="selectUnarchivedConversation"
      :select-unarchived-conversation-block="selectUnarchivedConversationBlock"
      :select-delegate-conversation="selectDelegateConversation"
      :select-remote-im-contact-conversation="selectRemoteImContactConversation"
      :select-remote-im-contact-conversation-block="selectRemoteImContactConversationBlock"
      :export-archive="exportArchive"
      :import-archive-file="prepareArchiveImport"
      :delete-archive="deleteArchive"
      :delete-unarchived-conversation="deleteUnarchivedConversation"
      :delete-delegate-conversation="deleteDelegateConversation"
      :delete-remote-im-contact-conversation="deleteRemoteImContactConversation"
      :close-memory-viewer="closeMemoryViewer"
      :prev-memory-page="() => { memoryPage--; }"
      :next-memory-page="() => { memoryPage++; }"
      :export-memories="exportMemories"
      :trigger-memory-import="triggerMemoryImport"
      :handle-memory-import-file="handleMemoryImportFile"
      :close-prompt-preview="closePromptPreview"
      :checking-update="checkingUpdate"
      :has-available-update="hasAvailableUpdate"
      :check-update="manualCheckGithubUpdate"
      :open-github="openGithubRepository"
      :last-saved-config-json="lastSavedConfigJson"
    />

    <ShellDialogsHost
      :update-dialog-open="updateDialogOpen"
      :update-dialog-title="updateDialogTitle"
      :update-dialog-body="updateDialogBody"
      :update-dialog-kind="updateDialogKind"
      :update-dialog-release-url="updateDialogReleaseUrl"
      :update-dialog-primary-action="updateDialogPrimaryAction"
      :update-progress-percent="updateProgressPercent"
      :runtime-logs-dialog-open="runtimeLogsDialogOpen"
      :runtime-logs="runtimeLogs"
      :runtime-logs-loading="runtimeLogsLoading"
      :runtime-logs-error="runtimeLogsError"
      :rewind-confirm-dialog-open="rewindConfirmDialogOpen"
      :rewind-confirm-can-undo-patch="rewindConfirmCanUndoPatch"
      :config-save-error-dialog-open="configSaveErrorDialogOpen"
      :config-save-error-dialog-title="configSaveErrorDialogTitle"
      :config-save-error-dialog-body="configSaveErrorDialogBody"
      :config-save-error-dialog-kind="configSaveErrorDialogKind"
      :archive-import-preview-dialog-open="archiveImportPreviewDialogOpen"
      :archive-import-preview="archiveImportPreview"
      :archive-import-running="archiveImportRunning"
      :skill-placeholder-dialog-open="skillPlaceholderDialogOpen"
      :trim-action-dialog-open="trimActionDialogOpen"
      :trim-preview-loading="trimPreviewLoading"
      :trim-preview="trimPreview"
      :trim-compaction-preview="trimCompactionPreview"
      :trimming="trimming"
      @close-update-dialog="closeUpdateDialog"
      @confirm-update-dialog-primary="confirmUpdateDialogPrimary"
      @open-update-release="openUpdateRelease"
      @close-runtime-logs-dialog="closeRuntimeLogsDialog"
      @refresh-runtime-logs="refreshRuntimeLogs"
      @clear-runtime-logs="clearRuntimeLogs"
      @confirm-rewind-with-patch="confirmRewindWithPatch"
      @confirm-rewind-message-only="confirmRewindMessageOnly"
      @cancel-rewind-confirm="cancelRewindConfirm"
      @close-settings-save-error-dialog="closeSettingsSaveErrorDialog"
      @close-archive-import-preview-dialog="closeArchiveImportPreviewDialog"
      @confirm-archive-import="confirmArchiveImport"
      @close-skill-placeholder-dialog="closeSkillPlaceholderDialog"
      @confirm-delete-conversation-from-archive-dialog="confirmDeleteConversationFromArchiveDialog"
      @confirm-trim-compaction-action="confirmTrimCompactionAction"
      @confirm-trim-action="handleConfirmTrimAction()"
      @close-trim-action-dialog="closeTrimActionDialog"
    />
    <Win10ResizeHandles :enabled="resizeHandlesEnabled" />
    <ChatWorkspacePickerDialog
      :open="chatWorkspacePickerOpen"
      :saving="chatWorkspacePickerSaving"
      :workspaces="chatWorkspaceDraftChoices"
      :autonomous-mode="chatWorkspaceDraftAutonomousMode"
      @close="closeChatWorkspacePicker"
      @add-workspace="addChatWorkspace"
      @set-main="setChatWorkspaceAsMain"
      @set-access="setChatWorkspaceAccess"
      @set-autonomous-mode="setChatWorkspaceAutonomousMode"
      @remove-workspace="removeChatWorkspace"
      @open-dir="openChatWorkspaceDir"
      @save="saveChatWorkspacePicker"
    />
    <div
      v-if="startupOverlayVisible"
      class="fixed inset-0 z-9998 flex items-center justify-center bg-base-300/90 p-6 backdrop-blur"
    >
      <div class="flex min-w-72 max-w-sm items-center gap-3 rounded-box border border-base-content/10 bg-base-100 px-5 py-4 shadow-2xl">
        <span class="loading loading-spinner loading-md text-primary"></span>
        <div class="min-w-0">
          <div class="font-medium">{{ startupOverlayMessage }}</div>
          <div class="mt-1 text-xs opacity-60">请稍候...</div>
        </div>
      </div>
    </div>
    <div
      v-if="messageStoreMigration.visible"
      class="fixed inset-0 z-9999 flex items-center justify-center bg-base-300/90 p-6 backdrop-blur"
    >
      <div class="w-full max-w-2xl rounded-box border border-base-content/10 bg-base-100 p-6 shadow-2xl">
        <div class="text-xl font-semibold">会话消息仓库迁移</div>
        <div class="mt-2 text-sm opacity-70">{{ messageStoreMigration.message }}</div>
        <progress
          v-if="messageStoreMigration.mode === 'migrating'"
          class="progress progress-primary mt-5 w-full"
          :value="messageStoreMigration.current"
          :max="Math.max(messageStoreMigration.total, 1)"
        />
        <div v-if="messageStoreMigration.mode === 'migrating'" class="mt-2 text-xs opacity-60">
          {{ messageStoreMigration.current }} / {{ messageStoreMigration.total }}
        </div>
        <div
          v-if="messageStoreMigration.blockedItems.length > 0"
          class="mt-5 max-h-64 space-y-2 overflow-auto rounded-box bg-base-200 p-3"
        >
          <div
            v-for="item in messageStoreMigration.blockedItems"
            :key="item.conversationId"
            class="rounded-box bg-base-100 p-3 text-sm"
          >
            <div class="font-medium">{{ item.title || item.conversationId }}</div>
            <div class="mt-1 text-xs opacity-60">{{ item.conversationId }}</div>
            <div class="mt-2 text-error">{{ item.reason || "未知错误" }}</div>
          </div>
        </div>
        <div v-if="messageStoreMigration.mode === 'blocked'" class="mt-5 flex justify-end gap-3">
          <button class="btn btn-ghost" @click="cancelMessageStoreMigration">取消启动</button>
          <button class="btn btn-error" @click="continueMessageStoreMigrationWithDiscard">
            抛弃异常会话并继续迁移
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import Win10ResizeHandles from "./features/shell/components/Win10ResizeHandles.vue";
import ChatWorkspacePickerDialog from "./features/chat/components/dialogs/ChatWorkspacePickerDialog.vue";
import AppWindowContent from "./features/shell/components/AppWindowContent.vue";
import AppWindowHeader from "./features/shell/components/AppWindowHeader.vue";
import ShellDialogsHost from "./features/shell/components/ShellDialogsHost.vue";
import { useChatWindowApp } from "./features/chat/composables/use-chat-window-app";

export default defineComponent({
  name: "ChatWindowApp",
  components: {
    Win10ResizeHandles,
    ChatWorkspacePickerDialog,
    AppWindowContent,
    AppWindowHeader,
    ShellDialogsHost,
  },
  setup() {
    return useChatWindowApp();
  },
});
</script>
