import { computed, nextTick } from "vue";
import { useI18n } from "vue-i18n";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { useAppCore } from "../../shell/composables/use-app-core";
import { useAppTheme } from "../../shell/composables/use-app-theme";
import { useWebviewZoomOrchestrator } from "../../shell/composables/use-webview-zoom-orchestrator";
import { usePipelineStatus } from "../../shell/composables/use-pipeline-status";
import { applyUiFont, normalizeUiFont } from "../../shell/composables/use-ui-font";
import { useMessageStoreMigrationGate } from "../../shell/composables/use-message-store-migration-gate";
import { useWindowActions } from "../../shell/composables/use-window-actions";
import { useWindowShell } from "../../shell/composables/use-window-shell";
import { searchConfigTabs } from "../../config/search/config-search";
import { useChatDialogRefs } from "./use-chat-dialog-refs";
import { useChatScrollCoordinator } from "./use-chat-scroll-coordinator";
import { useChatWindowShellDataOrchestrator } from "./use-chat-window-shell-data-orchestrator";
import { useChatWindowRuntimeOrchestrator } from "./use-chat-window-runtime-orchestrator";
import { useChatWindowContentOrchestrator } from "./use-chat-window-content-orchestrator";
import { useChatWindowWorkspaceOrchestrator } from "./use-chat-window-workspace-orchestrator";
import { useChatWindowLifecycleOrchestrator } from "./use-chat-window-lifecycle-orchestrator";
import { useChatWindowMediaOrchestrator } from "./use-chat-window-media-orchestrator";
import { useChatWindowState } from "./use-chat-window-state";
import { useChatUiStateOrchestrator } from "./use-chat-ui-state-orchestrator";
import { extractMessageImages, messageText } from "../../../utils/chat-message";
import { formatI18nError } from "../../../utils/error";
import type { AppConfig } from "../../../types/app";
import { normalizeLocale } from "../../../i18n";
import { resolveConversationDisplayTitle } from "../utils/conversation-title";
import { ensureConversationMessageIds } from "../utils/message-id";
import { useChatWindowConfigOrchestrator } from "./use-chat-window-config-orchestrator";

type ConversationActionsBridge = {
  refreshChatUnarchivedConversations: () => Promise<void>;
  freezeForegroundConversation: (reason: string) => void;
  sendChatFromCurrentWindow: (overrides?: { extraTextBlocks?: string[] }) => Promise<void>;
  detachCurrentConversationToWindow: (conversationId?: string) => Promise<void>;
  deleteUnarchivedConversationFromArchives: (conversationId: string) => Promise<void>;
  applyConversationRuntimeStateUpdated: (payload: { conversationId: string; runtimeState: "idle" | "assistant_streaming" | "organizing_context" }) => void;
};

export function useChatWindowApp() {
  const { t, locale } = useI18n();
  const tr = (key: string, params?: Record<string, unknown>) => (params ? t(key, params) : t(key));
  const isMacPlatform = /Mac|iPhone|iPad|iPod/i.test(window.navigator.platform || "");
  const {
    windowReady,
    alwaysOnTop,
    maximized,
    initWindow,
    syncWindowControlsState,
    closeWindow,
    startDrag,
    toggleAlwaysOnTop,
    minimizeWindow,
    toggleMaximizeWindow,
  } = useWindowShell();
  const {
    currentTheme,
    generatedThemeControls,
    generatedThemeTokens,
    applyTheme,
    setTheme,
    activateGeneratedTheme,
    updateGeneratedThemeControls,
    resetGeneratedTheme,
    restoreThemeFromStorage,
  } = useAppTheme();
  
  const {
    DRAFT_ASSISTANT_ID_PREFIX,
    BACKGROUND_CONVERSATION_CACHE_LIMIT,
    FOREGROUND_SNAPSHOT_RECENT_LIMIT,
    OLDER_HISTORY_PAGE_SIZE,
    viewMode,
    config,
    recordHotkeyProbeLastSeq,
    recordHotkeyProbeDown,
    chatWindowActiveSynced,
    tauriWindowLabel,
    isChatTauriWindow,
    detachedChatWindow,
    detachedChatConversationId,
    detachedTemporaryApiConfigId,
    chatWindowEventUnlisteners,
    currentChatConversationId,
    personas,
    assistantDepartmentAgentId,
    personaEditorId,
    userAlias,
    selectedResponseStyleId,
    selectedPdfReadMode,
    backgroundVoiceScreenshotKeywords,
    backgroundVoiceScreenshotMode,
    instructionPresets,
    conversationForegroundSyncing,
    backgroundConversationBadgeMap,
    conversationMessageCache,
    latestUserText,
    latestUserImages,
    latestAssistantText,
    latestReasoningStandardText,
    latestReasoningInlineText,
    latestOwnMessageAlignRequest,
    toolStatusText,
    toolStatusState,
    streamToolCalls,
    clipboardImages,
    queuedAttachmentNotices,
    allMessages,
    status,
    terminalApprovalQueue,
    terminalApprovalResolving,
    loading,
    saving,
    startupDataReady,
    startupOverlayVisible,
    startupOverlayMessage,
    chatting,
    trimming,
    compactingConversation,
    trimmingConversationId,
    compactingConversationId,
    suppressNextCompactionReload,
    branchingConversation,
    forwardingConversationSelection,
    hasMoreBackendHistory,
    loadingOlderConversationHistory,
    refreshingModels,
    modelRefreshError,
    modelRefreshOkFlags,
    checkingToolsStatus,
    toolStatuses,
    imageCacheStats,
    imageCacheStatsLoading,
    avatarSaving,
    avatarError,
    personaSaving,
    apiModelOptions,
    suppressAutosave,
    lastSavedConfigJson,
    lastSavedPersonasJson,
    PERF_DEBUG,
    CHAT_STREAM_DEBUG,
    toolReviewRefreshTick,
    currentChatTodos,
    foregroundTailLatestReady,
  } = useChatWindowState({
    isMacPlatform,
    t,
  });
  let conversationActions: ConversationActionsBridge = {
    refreshChatUnarchivedConversations: async () => {},
    freezeForegroundConversation: () => {},
    sendChatFromCurrentWindow: async () => {},
    detachCurrentConversationToWindow: async () => {},
    deleteUnarchivedConversationFromArchives: async () => {},
    applyConversationRuntimeStateUpdated: () => {},
  };
  const refreshChatUnarchivedConversations = () => conversationActions.refreshChatUnarchivedConversations();
  const freezeForegroundConversation = (reason: string) => conversationActions.freezeForegroundConversation(reason);
  const sendChatFromCurrentWindow = (overrides?: { extraTextBlocks?: string[] }) => conversationActions.sendChatFromCurrentWindow(overrides);
  const detachCurrentConversationToWindow = (conversationId?: string) => conversationActions.detachCurrentConversationToWindow(conversationId);
  const deleteUnarchivedConversationFromArchives = (conversationId: string) => conversationActions.deleteUnarchivedConversationFromArchives(conversationId);
  const applyConversationRuntimeStateUpdated: ConversationActionsBridge["applyConversationRuntimeStateUpdated"] =
    (payload) => conversationActions.applyConversationRuntimeStateUpdated(payload);
  const conversationApi = { bind: (actions: ConversationActionsBridge) => { conversationActions = actions; } };
  let chatFlow: any = null;
  let suppressNextOwnMessageAlignFromHistoryFlushed = 0;
  function bumpOwnUserDraftAlign() {
    suppressNextOwnMessageAlignFromHistoryFlushed += 1;
    latestOwnMessageAlignRequest.value += 1;
  }
  function consumeOrQueueOwnMessageAlign() {
    if (suppressNextOwnMessageAlignFromHistoryFlushed > 0) {
      suppressNextOwnMessageAlignFromHistoryFlushed -= 1;
      return;
    }
    latestOwnMessageAlignRequest.value += 1;
  }
  const {
    messageStoreMigration,
    ensureMessageStoreMigrationGate,
    cancelMessageStoreMigration,
    continueMessageStoreMigrationWithDiscard,
  } = useMessageStoreMigrationGate({
    formatRequestFailed: (error) => formatI18nError(tr, "status.requestFailed", error),
  });
  const { perfNow, perfLog, setStatus, setStatusError, localeOptions, applyUiLanguage } = useAppCore({
    t: tr,
    config,
    locale,
    status,
    perfDebug: PERF_DEBUG,
  });
  const {
    normalizeWebviewZoomPercent,
    updateWebviewZoomPercent,
    updateGithubUpdateMethod,
  } = useWebviewZoomOrchestrator({
    config,
    setStatusError,
  });
  const { clearConversationStatus } = usePipelineStatus({
    activeConversationId: computed(() => String(currentChatConversationId.value || "").trim()),
  });
  const chatUiState = useChatUiStateOrchestrator({
    viewMode,
    detachedChatWindow,
    currentChatConversationId,
    toolStatusState,
    clearConversationStatus: (conversationId, statusKind) => {
      clearConversationStatus(conversationId, statusKind);
    },
    searchConfigTabs,
    resolveConfigLocale: () => normalizeLocale(config.uiLanguage),
  });
  const {
    configTab,
    configSearchQuery,
    configSearchResults,
    selectedInstructionPrompts,
    selectedChatMentions,
    chatInput,
    conversationListTab,
    chatLeftPanelMode,
    chatRightPanelMode,
    sideConversationListVisible,
    toolReviewPanelOpenVisible,
    chatSidePanelWidths,
    chatErrorText,
    handleChatInputUpdate,
    updateConfigSearchQuery,
    handleSelectConfigSearchResult,
    updateSelectedInstructionPrompts,
    addChatMention,
    removeChatMention,
    handleSideConversationListVisibleChange,
    handleToolReviewPanelOpenChange,
    updateConversationListTab,
    updateChatLeftPanelMode,
    updateChatRightPanelMode,
    handleChatSidePanelWidthsChange,
    toggleSideConversationList,
    toggleToolReviewPanel,
    setConversationChatErrorText,
    clearMatchingConversationChatErrors,
    clearChatError,
  } = chatUiState;
  const shellData = useChatWindowShellDataOrchestrator({
    tr,
    viewMode,
    status,
    config,
    setStatus,
    setStatusError,
    currentChatConversationId,
  });
  const {
    unarchivedConversations,
    remoteImContactConversations,
    loadArchives,
    loadDelegateConversations,
    deleteUnarchivedConversation: deleteUnarchivedConversationFromArchivesRaw,
  } = shellData.archivesView;
  const { setConversationPlanMode } = shellData.conversationPlanMode;
  const {
    refreshActiveSupervisionTask,
    startSupervisionTaskPolling,
    clearSupervisionTaskPollTimer,
    handleConversationChanged: handleSupervisionConversationChanged,
  } = shellData.supervisionTask;
  const agentWorkPresence = shellData.agentWorkPresence;
  let refreshToolsStatus: () => void | Promise<void> = () => {};
  const configOrchestrator = useChatWindowConfigOrchestrator({
    t,
    config,
    locale,
    personas,
    configTab,
    apiModelOptions,
    modelRefreshOkFlags,
    lastSavedConfigJson,
    lastSavedPersonasJson,
    normalizeLocale,
    applyUiLanguage,
    refreshToolsStatus: () => refreshToolsStatus(),
    setStatus,
    setStatusError,
  });
  const {
    configDerived,
    configCore,
    configUi,
    configActions,
  } = configOrchestrator;
  const contentOrchestrator = useChatWindowContentOrchestrator({
    t,
    tr,
    viewMode,
    maximized,
    config,
    configDerived,
    locale,
    personas,
    assistantDepartmentAgentId,
    personaEditorId,
    currentChatConversationId,
    detachedChatWindow,
    detachedTemporaryApiConfigId,
    unarchivedConversations,
    remoteImContactConversations,
    backgroundConversationBadgeMap,
    allMessages,
    foregroundTailLatestReady,
    status,
    setStatus,
    setStatusError,
    selectedResponseStyleId,
    selectedPdfReadMode,
    backgroundVoiceScreenshotKeywords,
    backgroundVoiceScreenshotMode,
    instructionPresets,
    clipboardImages,
    queuedAttachmentNotices,
    normalizeLocale,
    PERF_DEBUG,
    perfNow,
    userAlias,
    agentWorkPresence,
    terminalApprovalQueue,
    terminalApprovalResolving,
  });
  const {
    selectedApiConfig,
    selectedApiProvider,
    normalizeRuntimeConfigNumbers,
    hasVisionFallback,
    activeSttApiConfig,
    shouldUseRemoteStt,
  } = configDerived;
  const chatMedia = useChatWindowMediaOrchestrator({
    tr,
    normalizeLocale,
    viewMode,
    config,
    status,
    setStatusError,
    chatting,
    trimming,
    chatInput,
    chatErrorText,
    clipboardImages,
    queuedAttachmentNotices,
    activeSttApiConfig,
    shouldUseRemoteStt,
    tauriWindowLabel,
    isChatTauriWindow,
    detachedChatWindow,
    currentChatConversationId,
    startupDataReady,
    recordHotkeyProbeLastSeq,
    recordHotkeyProbeDown,
    chatWindowActiveSynced,
    refreshChatUnarchivedConversations,
    freezeForegroundConversation,
    parseBackgroundVoiceScreenshotKeywords: (text: string) => parseBackgroundVoiceScreenshotKeywords(text),
    matchBackgroundVoiceScreenshotKeyword: (text: string, keywords: string[]) => matchBackgroundVoiceScreenshotKeyword(text, keywords),
    queueAutoScreenshotFromVoice: (input: {
      source: "local" | "remote";
      keyword: string;
      mode: "desktop" | "focused_window";
      startedAt: number;
    }) => queueAutoScreenshotFromVoice(input),
    backgroundVoiceScreenshotKeywords,
    backgroundVoiceScreenshotMode,
    sendChatFromCurrentWindow,
    getCurrentForegroundApiConfig: () => currentForegroundApiConfig.value,
    hasVisionFallback,
  });
  const { isChatWindowActiveNow } = chatMedia;
  const {
    conversationScrollToBottomRequest,
    clearPendingConversationScrollToBottomFallback,
    clearPendingManualScrollToBottom,
    triggerConversationScrollToBottom,
    scheduleConversationScrollToBottomFallback,
    setPendingManualScrollState,
    getPendingManualScrollToBottomConversationId,
    getPendingManualScrollToBottomRequestId,
  } = useChatScrollCoordinator({
    currentChatConversationId,
  });
  
  const {
    resolveAvatarUrl,
    ensureAvatarCached,
    preloadPersonaAvatars,
  } = contentOrchestrator.avatarCache;
  const {
    userPersona,
    assistantPersonas,
    currentForegroundConversationSummary,
    currentForegroundDepartmentId,
    currentForegroundAgentId,
    currentForegroundApiConfigId,
    currentForegroundApiConfig,
    currentForegroundPersona,
    selectedPersonaEditor,
    toolApiConfig,
    userPersonaAvatarUrl,
    currentForegroundPersonaAvatarUrl,
    selectedPersonaEditorAvatarUrl,
    chatPersonaAvatarUrlMap,
    createConversationDepartmentOptions,
  } = contentOrchestrator.personaConversation;
  const {
    openSettingsWindow,
    summonChatWindowFromConfig,
    closeWindowAndClearForeground,
    minimizeWindowAndClearForeground,
    openGithubRepository,
  } = useWindowActions({
    isChatTauriWindow,
    closeWindow,
    minimizeWindow,
    freezeForegroundConversation,
  });
  const workspaceOrchestrator = useChatWindowWorkspaceOrchestrator({
    currentForegroundApiConfigId,
    currentForegroundAgentId,
    currentChatConversationId,
    setStatus,
    setStatusError,
    tr,
  });
  const {
    chatWorkspaceName,
    refreshChatWorkspaceState,
  } = workspaceOrchestrator;
  const {
    createApiProvider,
    createApiConfig,
    normalizeApiBindingsLocal,
    buildConfigPayload,
    buildConfigSnapshotJson,
  } = configCore;
  const {
    defaultCreateConversationDepartmentId,
    responseStyleIds,
  } = configUi;

  const {
    syncUserAliasFromPersona,
    isLocalOwnUserMessage,
    isOptimisticOwnUserDraft,
    applySingleOwnUserHistoryFlushFastPath,
  } = contentOrchestrator.messageHelpers;
  
  const {
    updatePersonaEditorIdWithNotice,
    updateAssistantDepartmentAgentId,
    updateForegroundDepartmentPrimaryApiConfig,
    updateAssistantDepartmentApiConfigId,
    updateSelectedResponseStyleId,
    updateSelectedPdfReadMode,
    updateBackgroundVoiceScreenshotKeywords,
    updateBackgroundVoiceScreenshotMode,
    updateInstructionPresets,
    parseBackgroundVoiceScreenshotKeywords,
    matchBackgroundVoiceScreenshotKeyword,
    queueAutoScreenshotFromVoice,
  } = contentOrchestrator.localTools;
  const {
    buildPersonasSnapshotJson,
    setUiLanguage,
    importPersonaMemories,
    handleToolsChanged,
  } = configActions;

  const runtimeOrchestrator = useChatWindowRuntimeOrchestrator({
    DRAFT_ASSISTANT_ID_PREFIX,
    BACKGROUND_CONVERSATION_CACHE_LIMIT,
    FOREGROUND_SNAPSHOT_RECENT_LIMIT,
    OLDER_HISTORY_PAGE_SIZE,
    conversationApi,
    tr,
    setStatus,
    setStatusError,
    personas,
    assistantDepartmentAgentId,
    avatarSaving,
    avatarError,
    selectedApiConfig,
    selectedApiProvider,
    refreshingModels,
    modelRefreshError,
    apiModelOptions,
    modelRefreshOkFlags,
    toolApiConfig,
    checkingToolsStatus,
    toolStatuses,
    imageCacheStats,
    imageCacheStatsLoading,
    ensureAvatarCached,
    config,
    locale,
    normalizeLocale,
    suppressAutosave,
    loading,
    saving,
    personaSaving,
    assistantPersonas,
    personaEditorId,
    userAlias,
    selectedResponseStyleId,
    selectedPdfReadMode,
    backgroundVoiceScreenshotKeywords,
    backgroundVoiceScreenshotMode,
    instructionPresets,
    responseStyleIds,
    createApiConfig,
    normalizeApiBindingsLocal,
    buildConfigPayload,
    buildConfigSnapshotJson,
    buildPersonasSnapshotJson,
    lastSavedConfigJson,
    lastSavedPersonasJson,
    syncUserAliasFromPersona,
    preloadPersonaAvatars,
    selectedPersonaEditor,
    createApiProvider,
    chatErrorText,
    currentForegroundApiConfigId,
    currentForegroundAgentId,
    currentForegroundDepartmentId,
    currentForegroundConversationSummary,
    currentChatConversationId,
    currentChatTodos,
    trimmingConversationId,
    compactingConversationId,
    chatting,
    trimming,
    compactingConversation,
    suppressNextCompactionReload,
    allMessages,
    refreshChatUnarchivedConversations,
    perfNow,
    perfLog,
    PERF_DEBUG,
    configTab,
    tauriWindowLabel,
    unarchivedConversations,
    remoteImContactConversations,
    conversationForegroundSyncing,
    sideConversationListVisible,
    hasMoreBackendHistory,
    loadingOlderConversationHistory,
    foregroundTailLatestReady,
    chatWorkspaceName,
    conversationMessageCache,
    backgroundConversationBadgeMap,
    ensureConversationMessageIds,
    detachedChatWindow,
    detachedChatConversationId,
    detachedTemporaryApiConfigId,
    isChatWindowActiveNow,
    closeWindow,
    freezeForegroundConversation,
    clearPendingManualScrollToBottom,
    triggerConversationScrollToBottom,
    getPendingManualScrollToBottomConversationId,
    getPendingManualScrollToBottomRequestId,
    createConversationDepartmentOptions,
    defaultCreateConversationDepartmentId,
    branchingConversation,
    forwardingConversationSelection,
    deleteUnarchivedConversationFromArchivesRaw,
    getChatFlow: () => chatFlow,
    detachCurrentConversationToWindow,
    chatInput,
    selectedInstructionPrompts,
    selectedChatMentions,
    clipboardImages,
    queuedAttachmentNotices,
    latestUserText,
    latestUserImages,
    latestAssistantText,
    latestReasoningStandardText,
    latestReasoningInlineText,
    toolStatusText,
    toolStatusState,
    streamToolCalls,
    setConversationChatErrorText,
    bumpOwnUserDraftAlign,
    applySingleOwnUserHistoryFlushFastPath,
    consumeOrQueueOwnMessageAlign,
    isOptimisticOwnUserDraft,
    isLocalOwnUserMessage,
    deleteUnarchivedConversationFromArchives,
    sendChatFromCurrentWindow,
    setConversationPlanMode,
    messageText,
    extractMessageImages,
  });
  const {
    configRuntime,
    configPersistence,
    configEditors,
    chatRuntime,
    promptPreviewActions,
    memoryViewerActions,
    shellDialogFlows,
    chatDialogActions,
    conversationOrchestrator,
    handleConfirmPlan,
    deleteUnarchivedConversation,
    handleRecallTurn,
    handleRegenerateTurn,
  } = runtimeOrchestrator;
  chatFlow = runtimeOrchestrator.chatFlow;
  refreshToolsStatus = configRuntime.refreshToolsStatus;
  const {
    setMemoryDialogRef,
    setPromptPreviewDialogRef,
  } = useChatDialogRefs({
    memoryDialog: memoryViewerActions.memoryDialog,
    promptPreviewDialog: promptPreviewActions.promptPreviewDialog,
  });

  useChatWindowLifecycleOrchestrator({
    viewMode,
    config,
    locale,
    tr,
    perfNow,
    perfLog,
    setStatus,
    setStatusError,
    initWindow,
    applyTheme,
    restoreThemeFromStorage,
    normalizeLocale,
    normalizeWebviewZoomPercent,
    updateGithubUpdateMethod,
    applyUiFont,
    chatWindowEventUnlisteners,
    tauriWindowLabel,
    detachedChatWindow,
    isChatTauriWindow,
    currentChatConversationId,
    chatWindowActiveSynced,
    currentChatTodos,
    startupDataReady,
    startupOverlayVisible,
    startupOverlayMessage,
    toolReviewRefreshTick,
    recordHotkeyProbeLastSeq,
    recordHotkeyProbeDown,
    userAlias,
    selectedResponseStyleId,
    selectedPdfReadMode,
    backgroundVoiceScreenshotKeywords,
    backgroundVoiceScreenshotMode,
    instructionPresets,
    allMessages,
    conversationMessageCache,
    ensureConversationMessageIds,
    CHAT_STREAM_DEBUG,
    getChatFlow: () => chatFlow,
    ensureMessageStoreMigrationGate,
    syncWindowControlsState,
    autoCheckGithubUpdate: shellData.githubUpdate.autoCheckGithubUpdate,
    loadDelegateConversations,
    loadArchives,
    unarchivedConversations,
    agentWorkPresence,
    cancelPendingRewindConfirm: shellDialogFlows.cancelPendingRewindConfirm,
    handleSupervisionConversationChanged,
    clearSupervisionTaskPollTimer,
    startSupervisionTaskPolling,
    refreshActiveSupervisionTask,
    ...configDerived,
    ...configCore,
    ...configRuntime,
    ...configPersistence,
    ...chatRuntime,
    ...contentOrchestrator.terminalApproval,
    ...contentOrchestrator.personaConversation,
    ...contentOrchestrator.messageHelpers,
    ...chatUiState,
    ...chatMedia,
    ...workspaceOrchestrator,
    ...conversationOrchestrator,
    personas,
    userPersona: contentOrchestrator.personaConversation.userPersona,
    assistantPersonas: contentOrchestrator.personaConversation.assistantPersonas,
    assistantDepartmentAgentId,
    personaEditorId,
    selectedApiConfig: configDerived.selectedApiConfig,
    toolApiConfig: contentOrchestrator.personaConversation.toolApiConfig,
    modelRefreshError,
    toolStatuses,
  });
    return {
    messageText,
    extractMessageImages,
    viewMode,
    t,
    locale,
    tr,
    windowReady,
    maximized,
    startDrag,
    toggleMaximizeWindow,
    currentTheme,
    generatedThemeControls,
    generatedThemeTokens,
    setTheme,
    activateGeneratedTheme,
    updateGeneratedThemeControls,
    resetGeneratedTheme,
    config,
    detachedChatWindow,
    currentChatConversationId,
    personas,
    assistantDepartmentAgentId,
    personaEditorId,
    userAlias,
    selectedResponseStyleId,
    selectedPdfReadMode,
    backgroundVoiceScreenshotKeywords,
    backgroundVoiceScreenshotMode,
    instructionPresets,
    latestUserText,
    latestUserImages,
    latestAssistantText,
    latestReasoningStandardText,
    latestReasoningInlineText,
    latestOwnMessageAlignRequest,
    toolStatusText,
    toolStatusState,
    streamToolCalls,
    clipboardImages,
    queuedAttachmentNotices,
    status,
    terminalApprovalResolving,
    loading,
    saving,
    startupOverlayVisible,
    startupOverlayMessage,
    messageStoreMigration,
    chatting,
    trimming,
    compactingConversation,
    trimmingConversationId,
    compactingConversationId,
    branchingConversation,
    forwardingConversationSelection,
    hasMoreBackendHistory,
    loadingOlderConversationHistory,
    refreshingModels,
    modelRefreshError,
    toolStatuses,
    imageCacheStats,
    imageCacheStatsLoading,
    avatarSaving,
    avatarError,
    personaSaving,
    lastSavedConfigJson,
    setStatus,
    localeOptions,
    updateWebviewZoomPercent,
    updateGithubUpdateMethod,
    toolReviewRefreshTick,
    currentChatTodos,
    chatFlow,
    ...chatUiState,
    ...shellData.githubUpdate,
    ...shellData.archivesView,
    ...shellData.conversationPlanMode,
    ...shellData.supervisionTask,
    ...shellData.archiveImport,
    ...configDerived,
    ...configCore,
    ...configUi,
    ...configActions,
    ...contentOrchestrator.conversationItems,
    ...contentOrchestrator.personaConversation,
    ...contentOrchestrator.messageBlocks,
    ...contentOrchestrator.terminalApproval,
    ...contentOrchestrator.basicState,
    ...contentOrchestrator.localTools,
    ...chatMedia,
    ...workspaceOrchestrator,
    ...configRuntime,
    ...configPersistence,
    ...configEditors,
    ...promptPreviewActions,
    ...memoryViewerActions,
    ...shellDialogFlows,
    ...chatDialogActions,
    ...conversationOrchestrator,
    openSettingsWindow,
    summonChatWindowFromConfig,
    minimizeWindowAndClearForeground,
    openGithubRepository,
    conversationScrollToBottomRequest,
    handleConfirmPlan,
    deleteUnarchivedConversation,
    handleRecallTurn,
    handleRegenerateTurn,
    setMemoryDialogRef,
    setPromptPreviewDialogRef,
    cancelMessageStoreMigration,
    continueMessageStoreMigrationWithDiscard,
  };
}
