import { formatI18nError } from "../../../utils/error";
import { removeBinaryPlaceholders } from "../../../utils/chat-message";
import { useChatRuntimeSetup } from "./use-chat-runtime-setup";
import { useChatServiceAssemblies } from "./use-chat-service-assemblies";
import { useChatWindowConversationOrchestrator } from "./use-chat-window-conversation-orchestrator";

export function useChatWindowRuntimeOrchestrator(bindings: Record<string, any>) {
  let openSettingsSaveErrorDialog: (...args: any[]) => void = (..._args: unknown[]) => {};

  function setConversationRuntimeStateLocal(
    conversationId: string,
    runtimeState: "idle" | "assistant_streaming" | "organizing_context",
  ) {
    bindings.conversationApi.applyConversationRuntimeStateUpdated({
      conversationId,
      runtimeState,
    });
  }

  const serviceAssemblies = useChatServiceAssemblies({
    tr: bindings.tr,
    setStatus: bindings.setStatus,
    setStatusError: bindings.setStatusError,
    personas: bindings.personas,
    assistantDepartmentAgentId: bindings.assistantDepartmentAgentId,
    avatarSaving: bindings.avatarSaving,
    avatarError: bindings.avatarError,
    selectedApiConfig: bindings.selectedApiConfig,
    selectedApiProvider: bindings.selectedApiProvider,
    refreshingModels: bindings.refreshingModels,
    modelRefreshError: bindings.modelRefreshError,
    apiModelOptions: bindings.apiModelOptions,
    modelRefreshOkFlags: bindings.modelRefreshOkFlags,
    toolApiConfig: bindings.toolApiConfig,
    checkingToolsStatus: bindings.checkingToolsStatus,
    toolStatuses: bindings.toolStatuses,
    imageCacheStats: bindings.imageCacheStats,
    imageCacheStatsLoading: bindings.imageCacheStatsLoading,
    ensureAvatarCached: bindings.ensureAvatarCached,
    openSettingsSaveErrorDialog: (...args: unknown[]) => openSettingsSaveErrorDialog(...args),
    config: bindings.config,
    locale: bindings.locale,
    normalizeLocale: bindings.normalizeLocale,
    suppressAutosave: bindings.suppressAutosave,
    loading: bindings.loading,
    saving: bindings.saving,
    personaSaving: bindings.personaSaving,
    assistantPersonas: bindings.assistantPersonas,
    personaEditorId: bindings.personaEditorId,
    userAlias: bindings.userAlias,
    selectedResponseStyleId: bindings.selectedResponseStyleId,
    selectedPdfReadMode: bindings.selectedPdfReadMode,
    backgroundVoiceScreenshotKeywords: bindings.backgroundVoiceScreenshotKeywords,
    backgroundVoiceScreenshotMode: bindings.backgroundVoiceScreenshotMode,
    instructionPresets: bindings.instructionPresets,
    responseStyleIds: bindings.responseStyleIds,
    createApiConfig: bindings.createApiConfig,
    normalizeApiBindingsLocal: bindings.normalizeApiBindingsLocal,
    buildConfigPayload: bindings.buildConfigPayload,
    buildConfigSnapshotJson: bindings.buildConfigSnapshotJson,
    buildPersonasSnapshotJson: bindings.buildPersonasSnapshotJson,
    lastSavedConfigJson: bindings.lastSavedConfigJson,
    lastSavedPersonasJson: bindings.lastSavedPersonasJson,
    syncUserAliasFromPersona: bindings.syncUserAliasFromPersona,
    preloadPersonaAvatars: bindings.preloadPersonaAvatars,
    selectedPersonaEditor: bindings.selectedPersonaEditor,
    createApiProvider: bindings.createApiProvider,
    chatErrorText: bindings.chatErrorText,
    setConversationRuntimeState: setConversationRuntimeStateLocal,
    currentForegroundApiConfigId: bindings.currentForegroundApiConfigId,
    currentForegroundAgentId: bindings.currentForegroundAgentId,
    currentChatConversationId: bindings.currentChatConversationId,
    trimmingConversationId: bindings.trimmingConversationId,
    compactingConversationId: bindings.compactingConversationId,
    chatting: bindings.chatting,
    trimming: bindings.trimming,
    compactingConversation: bindings.compactingConversation,
    suppressNextCompactionReload: bindings.suppressNextCompactionReload,
    allMessages: bindings.allMessages,
    refreshChatUnarchivedConversations: bindings.refreshChatUnarchivedConversations,
    perfNow: bindings.perfNow,
    perfLog: bindings.perfLog,
    PERF_DEBUG: bindings.PERF_DEBUG,
    configTab: bindings.configTab,
    tauriWindowLabel: bindings.tauriWindowLabel,
    currentForegroundDepartmentId: bindings.currentForegroundDepartmentId,
    unarchivedConversations: bindings.unarchivedConversations,
    deleteUnarchivedConversationFromArchives: bindings.deleteUnarchivedConversationFromArchives,
  });

  const {
    chatRuntime,
    shellDialogFlows,
  } = serviceAssemblies;
  const { loadAllMessages } = chatRuntime;

  // Config persistence reports save errors through shell dialogs, but the shell
  // dialog flow is assembled in the same service graph. Keep this late-bound
  // edge explicit so the initialization order is visible at the call site.
  openSettingsSaveErrorDialog = shellDialogFlows.openSettingsSaveErrorDialog;

  const conversationOrchestrator = useChatWindowConversationOrchestrator({
    FOREGROUND_SNAPSHOT_RECENT_LIMIT: bindings.FOREGROUND_SNAPSHOT_RECENT_LIMIT,
    BACKGROUND_CONVERSATION_CACHE_LIMIT: bindings.BACKGROUND_CONVERSATION_CACHE_LIMIT,
    OLDER_HISTORY_PAGE_SIZE: bindings.OLDER_HISTORY_PAGE_SIZE,
    sync: {
      DRAFT_ASSISTANT_ID_PREFIX: bindings.DRAFT_ASSISTANT_ID_PREFIX,
      BACKGROUND_CONVERSATION_CACHE_LIMIT: bindings.BACKGROUND_CONVERSATION_CACHE_LIMIT,
      OLDER_HISTORY_PAGE_SIZE: bindings.OLDER_HISTORY_PAGE_SIZE,
      currentChatConversationId: bindings.currentChatConversationId,
      currentChatPreferredApiConfigId: bindings.currentChatPreferredApiConfigId,
      currentChatTodos: bindings.currentChatTodos,
      currentForegroundAgentId: bindings.currentForegroundAgentId,
      currentForegroundApiConfigId: bindings.currentForegroundApiConfigId,
      detachedChatConversationId: bindings.detachedChatConversationId,
      detachedChatWindow: bindings.detachedChatWindow,
      tauriWindowLabel: bindings.tauriWindowLabel,
      unarchivedConversations: bindings.unarchivedConversations,
      allMessages: bindings.allMessages,
      hasMoreBackendHistory: bindings.hasMoreBackendHistory,
      loadingOlderConversationHistory: bindings.loadingOlderConversationHistory,
      foregroundTailLatestReady: bindings.foregroundTailLatestReady,
      conversationMessageCache: bindings.conversationMessageCache,
      backgroundConversationBadgeMap: bindings.backgroundConversationBadgeMap,
      ensureConversationMessageIds: bindings.ensureConversationMessageIds,
      clearPendingManualScrollToBottom: bindings.clearPendingManualScrollToBottom,
      triggerConversationScrollToBottom: bindings.triggerConversationScrollToBottom,
      getPendingManualScrollToBottomConversationId: bindings.getPendingManualScrollToBottomConversationId,
      getPendingManualScrollToBottomRequestId: bindings.getPendingManualScrollToBottomRequestId,
      loadAllMessages,
      getChatFlow: () => bindings.getChatFlow(),
      readConversationStreamCache: (conversationId?: string | null) =>
        bindings.getChatFlow()?.readConversationStreamCache(conversationId) || null,
      setStatusError: bindings.setStatusError,
      perfNow: bindings.perfNow,
      tr: bindings.tr,
    },
    config: bindings.config,
    tr: bindings.tr,
    tauriWindowLabel: bindings.tauriWindowLabel,
    detachedChatWindow: bindings.detachedChatWindow,
    detachedChatConversationId: bindings.detachedChatConversationId,
    detachedTemporaryApiConfigId: bindings.detachedTemporaryApiConfigId,
    currentChatConversationId: bindings.currentChatConversationId,
    currentChatPreferredApiConfigId: bindings.currentChatPreferredApiConfigId,
    currentChatTodos: bindings.currentChatTodos,
    currentForegroundAgentId: bindings.currentForegroundAgentId,
    currentForegroundConversationSummary: bindings.currentForegroundConversationSummary,
    currentForegroundApiConfigId: bindings.currentForegroundApiConfigId,
    unarchivedConversations: bindings.unarchivedConversations,
    remoteImContactConversations: bindings.remoteImContactConversations,
    conversationForegroundSyncing: bindings.conversationForegroundSyncing,
    trimmingConversationId: bindings.trimmingConversationId,
    compactingConversationId: bindings.compactingConversationId,
    trimming: bindings.trimming,
    compactingConversation: bindings.compactingConversation,
    chatting: bindings.chatting,
    sideConversationListVisible: bindings.sideConversationListVisible,
    allMessages: bindings.allMessages,
    hasMoreBackendHistory: bindings.hasMoreBackendHistory,
    foregroundTailLatestReady: bindings.foregroundTailLatestReady,
    chatWorkspaceName: bindings.chatWorkspaceName,
    conversationMessageCache: bindings.conversationMessageCache,
    backgroundConversationBadgeMap: bindings.backgroundConversationBadgeMap,
    setStatus: bindings.setStatus,
    setStatusError: bindings.setStatusError,
    perfNow: bindings.perfNow,
    loadAllMessages,
    isChatWindowActiveNow: bindings.isChatWindowActiveNow,
    closeWindow: bindings.closeWindow,
    freezeForegroundConversation: bindings.freezeForegroundConversation,
    clearPendingManualScrollToBottom: bindings.clearPendingManualScrollToBottom,
    triggerConversationScrollToBottom: bindings.triggerConversationScrollToBottom,
    getPendingManualScrollToBottomConversationId: bindings.getPendingManualScrollToBottomConversationId,
    getPendingManualScrollToBottomRequestId: bindings.getPendingManualScrollToBottomRequestId,
    createConversationDepartmentOptions: bindings.createConversationDepartmentOptions,
    defaultCreateConversationDepartmentId: bindings.defaultCreateConversationDepartmentId,
    branchingConversation: bindings.branchingConversation,
    forwardingConversationSelection: bindings.forwardingConversationSelection,
    deleteUnarchivedConversationFromArchivesRaw: bindings.deleteUnarchivedConversationFromArchivesRaw,
    openTrimActionDialog: shellDialogFlows.openTrimActionDialog,
    confirmTrimAction: shellDialogFlows.confirmTrimAction,
    closeTrimActionDialog: shellDialogFlows.closeTrimActionDialog,
    archiveCurrentConversation: chatRuntime.trimNow,
    getChatFlow: () => bindings.getChatFlow(),
    detachCurrentConversationToWindow: bindings.detachCurrentConversationToWindow,
    waitPendingConversationPreferredModelPersist: bindings.waitPendingConversationPreferredModelPersist,
    openPromptPreview: () => serviceAssemblies.chatDialogActions.openPromptPreview,
  });

  bindings.conversationApi.bind({
    refreshChatUnarchivedConversations: conversationOrchestrator.refreshChatUnarchivedConversations,
    freezeForegroundConversation: conversationOrchestrator.freezeForegroundConversation,
    restoreForegroundConversationProjection: conversationOrchestrator.restoreForegroundConversationProjection,
    sendChatFromCurrentWindow: conversationOrchestrator.sendChatFromCurrentWindow,
    detachCurrentConversationToWindow: conversationOrchestrator.detachCurrentConversationToWindow,
    deleteUnarchivedConversationFromArchives: conversationOrchestrator.deleteUnarchivedConversationFromArchives,
    applyConversationRuntimeStateUpdated: conversationOrchestrator.applyConversationRuntimeStateUpdated,
  });

  const chatRuntimeSetup = useChatRuntimeSetup({
    chatRuntime,
    chatting: bindings.chatting,
    trimming: bindings.trimming,
    compactingConversation: bindings.compactingConversation,
    currentForegroundApiConfigId: bindings.currentForegroundApiConfigId,
    currentForegroundAgentId: bindings.currentForegroundAgentId,
    currentForegroundDepartmentId: bindings.currentForegroundDepartmentId,
    currentChatConversationId: bindings.currentChatConversationId,
    chatInput: bindings.chatInput,
    selectedChatMentions: bindings.selectedChatMentions,
    clipboardImages: bindings.clipboardImages,
    queuedAttachmentNotices: bindings.queuedAttachmentNotices,
    latestUserText: bindings.latestUserText,
    latestUserImages: bindings.latestUserImages,
    latestAssistantText: bindings.latestAssistantText,
    toolStatusText: bindings.toolStatusText,
    toolStatusState: bindings.toolStatusState,
    chatErrorText: bindings.chatErrorText,
    setConversationChatErrorText: bindings.setConversationChatErrorText,
    allMessages: bindings.allMessages,
    bumpOwnUserDraftAlign: bindings.bumpOwnUserDraftAlign,
    tr: bindings.tr,
    formatRequestFailed: (error: unknown) => formatI18nError(bindings.tr, "status.requestFailed", error),
    removeBinaryPlaceholders,
    reloadForegroundConversationMessages: conversationOrchestrator.reloadForegroundConversationMessages,
    tauriWindowLabel: bindings.tauriWindowLabel,
    isChatWindowActiveNow: bindings.isChatWindowActiveNow,
    applySingleOwnUserHistoryFlushFastPath: bindings.applySingleOwnUserHistoryFlushFastPath,
    consumeOrQueueOwnMessageAlign: bindings.consumeOrQueueOwnMessageAlign,
    cacheConversationMessages: conversationOrchestrator.cacheConversationMessages,
    insertMessagesBeforeAssistantDraft: conversationOrchestrator.insertMessagesBeforeAssistantDraft,
    reuseStableMessageReferences: conversationOrchestrator.reuseStableMessageReferences,
    foregroundTailLatestReady: bindings.foregroundTailLatestReady,
    isOptimisticOwnUserDraft: bindings.isOptimisticOwnUserDraft,
    isLocalOwnUserMessage: bindings.isLocalOwnUserMessage,
    maybeUpdateForegroundConversationOverviewFromLoadedMessages: conversationOrchestrator.maybeUpdateForegroundConversationOverviewFromLoadedMessages,
    deleteUnarchivedConversationFromArchives: bindings.deleteUnarchivedConversationFromArchives,
    sendChatFromCurrentWindow: bindings.sendChatFromCurrentWindow,
    setStatusError: bindings.setStatusError,
    messageText: bindings.messageText,
    extractMessageImages: bindings.extractMessageImages,
    requestRecallMode: shellDialogFlows.requestRecallMode,
    setConversationPlanMode: bindings.setConversationPlanMode,
    FOREGROUND_SNAPSHOT_RECENT_LIMIT: bindings.FOREGROUND_SNAPSHOT_RECENT_LIMIT,
    applyConversationSnapshot: conversationOrchestrator.applyConversationSnapshot,
  });

  return {
    ...serviceAssemblies,
    conversationOrchestrator,
    chatRuntimeSetup,
    chatFlow: chatRuntimeSetup.chatFlow,
    handleConfirmPlan: chatRuntimeSetup.handleConfirmPlan,
    deleteUnarchivedConversation: chatRuntimeSetup.deleteUnarchivedConversation,
    handleRecallTurn: chatRuntimeSetup.handleRecallTurn,
    handleRegenerateTurn: chatRuntimeSetup.handleRegenerateTurn,
  };
}
