import { useViewRefresh } from "../../shell/composables/use-view-refresh";
import { formatI18nError } from "../../../utils/error";
import { useChatRuntimeWatchers } from "./use-chat-runtime-watchers";
import { useChatWindowBootstrap } from "./use-chat-window-bootstrap";
import { useChatWindowEvents } from "./use-chat-window-events";
import { useChatWindowLifecycleSetup } from "./use-chat-window-lifecycle-setup";
import { useChatWindowWatchersGlue } from "./use-chat-window-watchers-glue";

export function useChatWindowLifecycleOrchestrator(bindings: Record<string, any>) {
  const { refreshAllViewData } = useViewRefresh({
    viewMode: bindings.viewMode,
    loadConfig: bindings.loadConfig,
    loadBootstrapSnapshot: bindings.loadBootstrapSnapshot,
    loadPersonas: bindings.loadPersonas,
    loadChatSettings: bindings.loadChatSettings,
    refreshImageCacheStats: bindings.refreshImageCacheStats,
    refreshConversationHistory: bindings.refreshConversationHistory,
    loadDelegateConversations: bindings.loadDelegateConversations,
    loadArchives: bindings.loadArchives,
    resetVisibleTurnCount: () => {},
    perfNow: bindings.perfNow,
    perfLog: bindings.perfLog,
    onRefreshStepSlow: (label, error) => {
      bindings.setStatus(`启动数据加载较慢：${label}：${formatI18nError(bindings.tr, "status.requestFailed", error)}`);
    },
    onRefreshStepFailed: (label, error) => {
      bindings.setStatus(`启动数据加载失败：${label}：${formatI18nError(bindings.tr, "status.requestFailed", error)}`);
    },
  });

  const appBootstrap = useChatWindowBootstrap({
    viewMode: bindings.viewMode,
    initWindow: bindings.initWindow,
    applyTheme: bindings.applyTheme,
    normalizeLocale: bindings.normalizeLocale,
    config: bindings.config,
    locale: bindings.locale,
    agentWorkPresence: bindings.agentWorkPresence,
    enqueueTerminalApprovalRequest: bindings.enqueueTerminalApprovalRequest,
    clearMatchingConversationChatErrors: bindings.clearMatchingConversationChatErrors,
    refreshConversationHistory: bindings.refreshConversationHistory,
    assistantDepartmentAgentId: bindings.assistantDepartmentAgentId,
    personaEditorId: bindings.personaEditorId,
    userAlias: bindings.userAlias,
    selectedResponseStyleId: bindings.selectedResponseStyleId,
    selectedPdfReadMode: bindings.selectedPdfReadMode,
    backgroundVoiceScreenshotKeywords: bindings.backgroundVoiceScreenshotKeywords,
    backgroundVoiceScreenshotMode: bindings.backgroundVoiceScreenshotMode,
    instructionPresets: bindings.instructionPresets,
    normalizeWebviewZoomPercent: bindings.normalizeWebviewZoomPercent,
    updateGithubUpdateMethod: bindings.updateGithubUpdateMethod,
    normalizeRuntimeConfigNumbers: bindings.normalizeRuntimeConfigNumbers,
    createApiConfig: bindings.createApiConfig,
    buildConfigSnapshotJson: bindings.buildConfigSnapshotJson,
    lastSavedConfigJson: bindings.lastSavedConfigJson,
    toolReviewRefreshTick: bindings.toolReviewRefreshTick,
    currentChatConversationId: bindings.currentChatConversationId,
    recordHotkeyProbeLastSeq: bindings.recordHotkeyProbeLastSeq,
    recordHotkeyProbeDown: bindings.recordHotkeyProbeDown,
    isPrimaryChatWindow: bindings.isPrimaryChatWindow,
    startRecording: bindings.startRecording,
    stopRecording: bindings.stopRecording,
  });

  useChatWindowEvents({
    unlisteners: bindings.chatWindowEventUnlisteners,
    tauriWindowLabel: bindings.tauriWindowLabel,
    detachedChatWindow: bindings.detachedChatWindow,
    isChatTauriWindow: bindings.isChatTauriWindow,
    sideConversationListVisible: bindings.sideConversationListVisible,
    toolReviewPanelOpenVisible: bindings.toolReviewPanelOpenVisible,
    readConversationIdFromPayload: bindings.readConversationIdFromPayload,
    currentChatConversationId: bindings.currentChatConversationId,
    matchesForegroundConversation: bindings.matchesForegroundConversation,
    getChatFlow: bindings.getChatFlow,
    mergeIncomingMessagesIntoCache: bindings.mergeIncomingMessagesIntoCache,
    readMessagesFromPayload: bindings.readMessagesFromPayload,
    setConversationBadge: bindings.setConversationBadge,
    formalizeConversationMessages: bindings.formalizeConversationMessages,
    conversationMessageCache: bindings.conversationMessageCache,
    cacheConversationMessages: bindings.cacheConversationMessages,
    applyConversationOverviewAppendedMessage: bindings.applyConversationOverviewAppendedMessage,
    clearConversationBadge: bindings.clearConversationBadge,
    toolReviewRefreshTick: bindings.toolReviewRefreshTick,
    updateForegroundConversationOverviewFromMessages: bindings.updateForegroundConversationOverviewFromMessages,
    applyConversationTodosUpdated: bindings.applyConversationTodosUpdated,
    applyConversationPinUpdated: bindings.applyConversationPinUpdated,
    applyConversationRuntimeStateUpdated: bindings.applyConversationRuntimeStateUpdated,
    applyConversationOverviewUpdated: bindings.applyConversationOverviewUpdated,
    CHAT_STREAM_DEBUG: bindings.CHAT_STREAM_DEBUG,
    applyConversationMessagesAfterSynced: bindings.applyConversationMessagesAfterSynced,
    applyConversationMessageAppended: bindings.applyConversationMessageAppended,
    scheduleChatWindowActiveStateSync: bindings.scheduleChatWindowActiveStateSync,
    startSupervisionTaskPolling: bindings.startSupervisionTaskPolling,
    refreshActiveSupervisionTask: bindings.refreshActiveSupervisionTask,
    handleWindowFocusForStateSync: bindings.handleWindowFocusForStateSync,
    handleWindowBlurForStateSync: bindings.handleWindowBlurForStateSync,
    handleVisibilityForStateSync: bindings.handleVisibilityForStateSync,
    handleWindowFocusForMicPrewarm: bindings.handleWindowFocusForMicPrewarm,
    handleVisibilityForMicPrewarm: bindings.handleVisibilityForMicPrewarm,
    clearChatWindowActiveSyncTimer: bindings.clearChatWindowActiveSyncTimer,
    clearChatMicPrewarmTimer: bindings.clearChatMicPrewarmTimer,
    clearSupervisionTaskPollTimer: bindings.clearSupervisionTaskPollTimer,
    clearForegroundConversationCacheRaf: bindings.clearForegroundConversationCacheRaf,
    clearRecordHotkeyProbeState: bindings.clearRecordHotkeyProbeState,
    agentWorkPresence: bindings.agentWorkPresence,
    chatWindowActiveSynced: bindings.chatWindowActiveSynced,
    isPrimaryChatWindow: bindings.isPrimaryChatWindow,
    cancelPendingRewindConfirm: bindings.cancelPendingRewindConfirm,
  });

  useChatWindowWatchersGlue({
    viewMode: bindings.viewMode,
    config: bindings.config,
    currentChatConversationId: bindings.currentChatConversationId,
    currentForegroundApiConfigId: bindings.currentForegroundApiConfigId,
    currentForegroundApiConfig: bindings.currentForegroundApiConfig,
    currentForegroundAgentId: bindings.currentForegroundAgentId,
    hasVisionFallback: bindings.hasVisionFallback,
    unarchivedConversations: bindings.unarchivedConversations,
    startupDataReady: bindings.startupDataReady,
    chatWorkspaceName: bindings.chatWorkspaceName,
    scheduleChatWindowActiveStateSync: bindings.scheduleChatWindowActiveStateSync,
    handleSupervisionConversationChanged: bindings.handleSupervisionConversationChanged,
    clearMatchingConversationChatErrors: bindings.clearMatchingConversationChatErrors,
    refreshChatWorkspaceState: bindings.refreshChatWorkspaceState,
    syncCurrentConversationWorkspaceLabel: bindings.syncCurrentConversationWorkspaceLabel,
    handleWindowFocusForMicPrewarm: bindings.handleWindowFocusForMicPrewarm,
    applyUiFont: bindings.applyUiFont,
  });

  useChatRuntimeWatchers({
    viewMode: bindings.viewMode,
    currentForegroundDepartmentId: bindings.currentForegroundDepartmentId,
    currentForegroundAgentId: bindings.currentForegroundAgentId,
    currentChatConversationId: bindings.currentChatConversationId,
    startupDataReady: bindings.startupDataReady,
    tauriWindowLabel: bindings.tauriWindowLabel,
    allMessages: bindings.allMessages,
    setStatusError: bindings.setStatusError,
    refreshChatUnarchivedConversations: bindings.refreshChatUnarchivedConversations,
    getChatFlow: bindings.getChatFlow,
    maybeResumeForegroundStreamingDraft: bindings.maybeResumeForegroundStreamingDraft,
    resumeForegroundRuntimeFromBackend: bindings.resumeForegroundRuntimeFromBackend,
    scheduleForegroundConversationCachePersist: bindings.scheduleForegroundConversationCachePersist,
  });

  useChatWindowLifecycleSetup({
    appBootstrap,
    restoreThemeFromStorage: bindings.restoreThemeFromStorage,
    onPaste: bindings.onPaste,
    onDragOver: bindings.onDragOver,
    onDrop: bindings.onDrop,
    onNativeFileDrop: bindings.onNativeFileDrop,
    mediaDragActive: bindings.mediaDragActive,
    recordHotkey: bindings.recordHotkey,
    ensureMessageStoreMigrationGate: bindings.ensureMessageStoreMigrationGate,
    refreshAllViewData,
    startupDataReady: bindings.startupDataReady,
    currentChatConversationId: bindings.currentChatConversationId,
    refreshChatUnarchivedConversations: bindings.refreshChatUnarchivedConversations,
    viewMode: bindings.viewMode,
    syncWindowControlsState: bindings.syncWindowControlsState,
    stopRecording: bindings.stopRecording,
    cleanupSpeechRecording: bindings.cleanupSpeechRecording,
    cleanupChatMedia: bindings.cleanupChatMedia,
    startupOverlayVisible: bindings.startupOverlayVisible,
    startupOverlayMessage: bindings.startupOverlayMessage,
    setStatus: bindings.setStatus,
    formatRequestFailed: (error: unknown) => formatI18nError(bindings.tr, "status.requestFailed", error),
    initializeDetachedChatWindow: bindings.initializeDetachedChatWindow,
    autoCheckGithubUpdate: bindings.autoCheckGithubUpdate,
    config: bindings.config,
    configTab: bindings.configTab,
    personas: bindings.personas,
    userPersona: bindings.userPersona,
    assistantPersonas: bindings.assistantPersonas,
    assistantDepartmentAgentId: bindings.assistantDepartmentAgentId,
    personaEditorId: bindings.personaEditorId,
    selectedApiConfig: bindings.selectedApiConfig,
    toolApiConfig: bindings.toolApiConfig,
    modelRefreshError: bindings.modelRefreshError,
    toolStatuses: bindings.toolStatuses,
    defaultApiTools: bindings.defaultApiTools,
    tr: bindings.tr,
    normalizeApiBindingsLocal: bindings.normalizeApiBindingsLocal,
    syncUserAliasFromPersona: bindings.syncUserAliasFromPersona,
    syncTrayIcon: bindings.syncTrayIcon,
    refreshToolsStatus: bindings.refreshToolsStatus,
    refreshImageCacheStats: bindings.refreshImageCacheStats,
  });
}
